### PR TITLE
Fix(Duplicate Alias):Added check if Alias is duplicated

### PR DESCRIPTION
**Pull request by agbilotia1998**
Fixes: Duplicate Aliases problem.

Error is thrown at time of form submission if alias is duplicated.

A check function is added to check if added alias is already present in AliasSet.

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@LordSputnik @leftmostcat please review.

**Comment by LordSputnik** [comment]
Hi Ayush, we currently don't have a lot of time to review contributions to BookBrainz because we're mentoring for Google Code In. But we do appreciate the work you're doing and will look at it as soon as possible. Thanks!

**Comment by LordSputnik** [comment]
Just took a quick look. I don't think we want this check to cause an error, because there are many valid cases where an entity will have the same alias as another entity. It would be better to warn the user that the entity they're adding might already be in the database.

To do that, I think the best thing to do would be to update the "NameSection" component to do an async request to the server search with the name the user entered.

**Comment by agbilotia1998** [comment]
Okay I will do that.

**Pull request closed without merging**
