### PR TITLE
feat(search): The aliases are now searchable.

### PR DESCRIPTION
**Pull request by panwarabhishek345**
### Problem
#BB-310 Search for entity by alias added and was not possible earlier.

### Solution
Added multi_match query and indexed entity aliases in elastic search.

### Areas of Impact
src/server/helpers/search.js

### CODE REVIEW

**Comment by MonkeyDo** [comment]
:tada:
Good choice of issue, that's a great improvement for an easy solution !

I'm not going to merge this right now, even though the search page part works perfectly, because there are other areas that use the search, and I need to determine if including aliases is what we want everywhere.

For example, when creating a new entity, we do a search based on the name to see if the new entity would be a possible duplicate. I am not 100% sure yet that searching for aliases here would be okay, and it might depend on the entity type.

Capture d’écran 2019-11-05 à 13 17 27

**Comment by panwarabhishek345** [comment]
That's totally fine!

**Comment by MonkeyDo** [comment]
I thought about this a bit more, and did some testing.

First of all, my concerns over what other components it could affect were unfounded, so that's good !

Second, I think you can actually revert to a single `match` query where you used a multi_match, but change the indexing so that `'aliasSet.aliases'` is indexed instead of `defaultAlias`.
The reason for that is that the defaultAlias is already on of the aliases contained in aliasSet.aliases.

**Comment by panwarabhishek345** [comment]
@MonkeyDo That's great. If it is then yes, we can use single match query. And what about the "creating a new entity" page?

**Comment by MonkeyDo** [comment]
That uses another mechanism to do the search on the database, and is unaffected by the changes in this PR.


I did find an important bug however, when testing the search component in the relationship editor.
Since you're working on search functionality, I figured you might be interested in having a go at it: https://tickets.metabrainz.org/browse/BB-361
It's another component entirely, but uses the results of the work you did in this PR

**Comment by panwarabhishek345** [comment]
@MonkeyDo  Made the appropriate changes to the commit. Now only aliasSet.aliases is indexed and queried.

**Comment by MonkeyDo** [comment]
OK, I've done more testing, and I am satisfied this PR works nicely with no undesirable side-effects !

Thank you !

**Comment by panwarabhishek345** [comment]
Perfect!

**Pull request merged**
