### PR TITLE
Delete collection from Elasticsearch index

### PR DESCRIPTION
**Pull request by prabalsingh24**
### Problem
After deleting the collection from Database, it has to be deleted from ES index as well

### CODE REVIEW

**Comment by prabalsingh24** [comment]
I've seen that sometimes `UserCollection({id: 1}).fetchAll()` gives incorrect result. whereas with `fetch` it works fine.  <br>
When i have to use `fetch` , I use `UserCollection({id: 1}).fetch()` whereas when i have to do `fetchAll` I use `UserCollection().where('id', 1).fetchAll`

**Comment by MonkeyDo** [comment]
Huh, interesting. I wonder why that is.
Thanks for the tip!

**Comment by prabalsingh24** [comment]
I could be wrong too. But i experienced it at many places.

**Comment by prabalsingh24** [comment]
Next time i see a similar issue, I'll check it properly. Will use debug true and see what happens

**Pull request merged**
