### PR TITLE
fix(static): Fixed the Navigation bar buttons (eg. Add button) staying highlighted after clicking on them the second time

### PR DESCRIPTION
**Pull request by panwarabhishek345**
### Problem
fix(static): Fixed the Navigation bar buttons (eg. Add button) staying highlighted after clicking on them the second time

### Solution
Added a method to prevent default behavior related to the focus on clicking a button.

### Areas of Impact
Layout component which is in the layout.js file

### CODE REVIEW

**Comment by MonkeyDo** [comment]
Hi @panwarabhishek345 !
Thanks a lot for your PR !

I'm away from my computer at the moment, but I'll be sure to review the PR when I'm back on !

**Comment by panwarabhishek345** [comment]
> Hi @panwarabhishek345 !
> Thanks a lot for your PR !
> 
> I'm away from my computer at the moment, but I'll be sure to review the PR when I'm back on !
Alright Looking forward to it

**Comment by panwarabhishek345** [comment]
@MonkeyDo Alright Looking Forward it to,

**Comment by MonkeyDo** [comment]
Hi @panwarabhishek345 !

First of all, thanks for looking into these issues and opening a PR !
Welcome to the community !

I have two main bits of feedback:

1. You are addressing two different issues (dropdown, 500 error), and each should be in a separate pull request. I know it may look silly to create a new branch and open a new PR for a few characters changed on a single file, but this allows us to follow where code was changed and why.
I can manage to clean up this PR 304 to keep only the dropdown related commits, and I would love it if you opened another one for the 500 error.
When you create the 500 error PR, you can also mention the issue ID for reference (BB-353) and it will automatically link the issue to the PR.
2. I can't understand what the navbar dropdown issue you're trying to fix is. Could you explain what you see and take some screenshots to illustrate? It may be that it is specific to certain browsers.
For reference, for me:
    - when I do a normal click in a navbar dropdown, I navigate away from the page.
    - when I do an open-in-a-new-tab click the dropdown stays open and highlighted until I click somewhere else, which I don't find too bothering.
    - I don't see any difference between running your code and on bookbrainz.org

**Comment by panwarabhishek345** [comment]
Hi! Mr. Monkey!
1. I will create a new branch with a new PR for 500 error issue.
2. The navbar issue is that when you first click the add button the
drop-down appears, then you press it again so the drop-down disappears. But
when you move the cursor away, the button still remains pressed even though
the drop-down is closed. I have fixed this issue. Please see the video
attached which shows the issue. Also, this is not browser-specific as this
happens with Firefox Browser too.

**Comment by panwarabhishek345** [comment]
Hello!
Also could you please assign these two bugs to me on the MetaBrainz JIRA!
Thanks
Abhishek Panwar

**Comment by MonkeyDo** [comment]
OK, thanks for explaining the issue, I see it now.
Thanks and well done on fixing it, that's clean and simple!

I will rewrite the commit history to remove the 500 error commit on this PR, and then merge it.

Regarding the Jira issues, you should be able (and encouraged !) to assign them to you yourself.

**Pull request merged**
