### PR TITLE
Protechthor edit-note 1

### PR DESCRIPTION
**Pull request by PROTechThor**
### Problem
The nature of the edit note request blurb

### Solution
Provision of a new blurb

### Areas of Impact
The submission-section.js file.

### CODE REVIEW

**Comment by PROTechThor** [comment]
@MonkeyDo Even after reverting the commits, there still seems to be a mixup? Should all the commits show in a row as such? Shouldn't just one be visible? I feel I've gone wrong somewhere.

**Comment by TheFaR8** [comment]
Tips
1. Learn how to operate git in your computer (such as ```git add```, ```git commit```, ```git push```, ```git fetch```
2. If you open a PR, stay on the branch you opened the PR.. If you commit to your branch, the PR will automatically updated too..
3. Learn ```git rebase``` too :)

**Comment by MonkeyDo** [comment]
OK @PROTechThor , thanks for those changes!
I'll be able to merge the PR as a single commit, so no problem there as long as we end up with the right file modifications :)

I'll merge that now and validate the task.

**Comment by MonkeyDo** [comment]
@PROTechThor For some reason, It appears I also need you to write any message in the GCI task before I can validate it.
https://codein.withgoogle.com/dashboard/task-instances/5909271213506560/

**Pull request merged**
