### PR TITLE
chore: updated the version of eslint dependencies

### PR DESCRIPTION
**Pull request by pv-912**
### Problem
Many devDependencies like eslint, web pack, babel and loaders are of old version.

### Solution
Updated devDependencies to their latest version.

### Areas of Impact
Building of application during development.

### CODE REVIEW

**Comment by pv-912** [comment]
I have not updated the main dependencies version as I was not sure about them. Once I will get more confident with the code I will update them too.

**Comment by pv-912** [comment]
Okay, I will try to check and update the dependencies into different types of packages as said above. Also, I have approximately checked the dependencies by running the components using them. However, I will do it again into parts.

**Comment by pv-912** [comment]
@MonkeyDo I have replaced this pr for updating eslint's module version only and made the required changes. Please review it.

**Comment by MonkeyDo** [comment]
Hi @pv-912 !
Would you like to complete this PR?
If not don't worry about it, I will simply close it and wait for a need to update these packages.

**Comment by pv-912** [comment]
> Hi @pv-912 !
> Would you like to complete this PR?
> If not don't worry about it, I will simply close it and wait for a need to update these packages.

Yes, u can close it as I am not much updated about it.

**Pull request closed without merging**
