### PR TITLE
[WIP] Duplication refactoring

### PR DESCRIPTION
**Pull request by naiveaiguy**
**WARNING**: In a perhaps futile effort to keep the history clean, I am performing `--amend` and history-rewriting commits every now and then when I spot that I've done something unbearably stupid. 

Work is ongoing. Currently have a `npm` task called `dupreport` that simply runs `jsinspect`. Will fix as many issues raised by it as I can, then fill out the template.

See current `dupreport` here: (*EDIT*: I gave up trying to mantain the Markdown, it's the raw output now)

<a href="https://gist.github.com/naiveaiguy/1eb8a12f2aa75876a1729d6f0bff1c10">gist.github.com/naiveaiguy/1eb8a12f2aa75876a1729d6f0bff1c100</a>

- [ ] sign commits. Am pushing from VM which does not have my GPG keys loaded. Will sign the commits from my non-VM environment later.

### CODE REVIEW

**Comment by naiveaiguy** [comment]
See current dupreport here:
<a href="https://gist.github.com/naiveaiguy/1eb8a12f2aa75876a1729d6f0bff1c10">gist.github.com/naiveaiguy/1eb8a12f2aa75876a1729d6f0bff1c10</a>

**Comment by naiveaiguy** [comment]
Just a thought, would it make sense to disable `coveralls` on PRs that have `[WIP]` or some such in the title?

**Comment by LordSputnik** [comment]
@naiveaiguy it would, but I don't believe coveralls supports that functionality.

**Comment by naiveaiguy** [comment]
See #174 for a PR that's not an abomination. It's for cases like this that I wish GitHub would allow us to delete PRs.

Mistakes were made.

**Pull request closed without merging**
