### PR TITLE
fix: added compression middleware

### PR DESCRIPTION
**Pull request by falafel72**
### Problem
Server responses can be slow for people with low bandwidth. 

### Solution
Adding the node "compression" module to compress all incoming responses.

### CODE REVIEW

**Comment by Arthelon** [comment]
@falafel72 Could you make sure your code conforms with the project's eslint rules? (Try running `npm run lint-errors`)

**Comment by falafel72** [comment]
Just ran it, apart from minor issues with organisation there didn't seem to be any problems.

**Comment by Arthelon** [comment]
Looks good to me. Thanks! 

@LordSputnik

**Comment by LordSputnik** [comment]
Great work @falafel72

**Pull request merged**
