### PR TITLE
BB-373 React fontawesome — entity image

### PR DESCRIPTION
**Pull request by prabalsingh24**
### Problem
https://tickets.metabrainz.org/browse/BB-373
https://tickets.metabrainz.org/browse/BB-386
Migrating React-FontAwesome : entities/image.js

Note from MonkeyDo: I also hijacked the PR to finish cleaning up the unused FontAwesome files made obsolete by the package change ([BB-386](https://tickets.metabrainz.org/browse/BB-386))

### Areas of Impact
src/client/components/pages/entities/image.js

### CODE REVIEW

**Comment by MonkeyDo** [comment]
If you're getting a 500 error when trying to visit an entity, that's because of a mismatch of bookbrainz-data package with the ROM update business.

Easy fix: merge or rebase master and it should work.

**Comment by MonkeyDo** [comment]
@prabalsingh24 I know you're already well busy writing tests and new PRs, but I'd love it if we could focus on closing up the FontAwesome job (finishing replacing the library, cleanup, and figuring out vertical alignment of the icons).
Let me know if you need a hand

**Comment by prabalsingh24** [comment]
I will finish this asap. :) Sorry for the delay

**Comment by MonkeyDo** [comment]
> I will finish this asap. :) Sorry for the delay

No problem, I just wanted to make sure they're not forgotten, and to tie our loose ends :)

**Comment by MonkeyDo** [comment]
I'd love to close up the FontAwesome update chapter before publishing a new version of the website.
Do you want me to have a look at finishing up the remaining PRs?

**Comment by MonkeyDo** [comment]
>MonkeyDo approved these changes

**Pull request merged**
