### PR TITLE
Refactored footer of entity display component

### PR DESCRIPTION
**Pull request by endurance21**
# Problem
* ## Non Responsive footer on entity pages.
Screenshot from 2021-03-21 13-34-23

# Solution
* ## Revamped the layout structure and added "no-gutter" utility class that was missing in bootstrap 3 that we are using.
Screenshot from 2021-03-21 13-34-53

### Areas of Impact
src/client/components/pages/entities/footer.js
src/client/stylesheets/style.less

### CODE REVIEW

**Comment by endurance21** [comment]
@MonkeyDo please have a look.

**Review by akashgp09 — COMMENTED** [review]
PR #568  already fixes this

**Comment by endurance21** [comment]
sorry that i did not checked the related PR.
I liked you approached too !
though i have added some css utility like `no-gutter` , i think that is very imp nowdays.
Lets see what @MonkeyDo says then we can take action on this pr !

**Comment by akashgp09** [comment]
> sorry that i did not checked the related PR.

I see you have some code reviews on that PR :)

**Comment by endurance21** [comment]
@akashgp09  I think I reviewed it a while ago and it was just code wise and I do review a lot of pr in a while so maybe it didn't cross my mind .

**Comment by endurance21** [comment]
It's okay we can close this one !$

**Comment by MonkeyDo** [comment]
Yes, let's focus on #568 .
@endurance21 it's important to check if a ticket is already assigned in JIRA before starting any work.
If it has been assigned for along time (say a year ago) then it is probably fine to reassign; in other cases, time to find another ticket :)

**Pull request closed without merging**
