### PR TITLE
BB-443: Revision Notes Ordering

### PR DESCRIPTION
**Pull request by prabalsingh24**
### Problem
https://tickets.metabrainz.org/projects/BB/issues/BB-443
Revision Notes were not sorted.
Screenshot_2020-03-16 BookBrainz – The Open Book Database(3)
Screenshot_2020-03-16 BookBrainz – The Open Book Database(2)

### Solution

Sorted the notes while fetching them. </br>
Screenshot_2020-03-16 BookBrainz – The Open Book Database(1)
Screenshot_2020-03-16 BookBrainz – The Open Book Database

### Areas of Impact

src/server/routes/editor.js
src/server/routes/revision.js

### CODE REVIEW

**Comment by prabalsingh24** [comment]
I will write test for this as well :)

**Comment by prabalsingh24** [comment]
Should this be sorted in descending order?

**Comment by MonkeyDo** [comment]
> Should this be sorted in descending order?

I think this works well as it is, in case there is a 'discussion' note after note.
If someone makes a compelling case in the future why they should be sorted the descending, we'll think about it then.

**Comment by prabalsingh24** [comment]
I think this can be merged now. I've written tests for this in [385](https://github.com/bookbrainz/bookbrainz-site/pull/385)

**Pull request merged**
