### PR TITLE
Installation troubleshooting

### PR DESCRIPTION
**Pull request by PROTechThor**
### Problem
While installing the bookbrainz server locally, errors may arise

### Solution
A troubleshoot guide with some sample errors and possible solutions.

### Areas of Impact
No area of the codebase is affected, I think.

### CODE REVIEW

**Comment by PROTechThor** [comment]
@MonkeyDo What do you think?

**Comment by MonkeyDo** [comment]
Hi @ProTechTor!
Thanks for the PR!

I'll be able to look at it either tomorrow or Monday morning (GMT+1). I look forward to it :)

**Comment by MonkeyDo** [comment]
I suggest to reorganize the errors by categories:
- General
- ElasticSearch
- PostgreSQL
- Redis
- Node/NPM

Currently in the document there are 4 errors. They should fit like this:
1. General
2. PostgreSQL
3. Node/NPM
4. PostgreSQL

**Comment by PROTechThor** [comment]
@MonkeyDo Got it. :) I'll edit it as such.

**Comment by TheFaR8** [comment]
I've made a PR to your repo

https://github.com/PROTechThor/bookbrainz-site/pull/2

**Comment by MonkeyDo** [comment]
That's great @PROTechThor, thank you!

**Pull request merged**
